version: '3.1'
services:
  sandbox-task:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=sandbox
      - SPRING_DATASOURCE_PASSWORD=sandbox
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgre_sql
    ports:
      - "8080:8080"



  postgre_sql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_USER=sandbox
      - POSTGRES_DB=sandbox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
