spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${JDBC_URL:localhost}:${JDBC_PORT:5432}/${DATABASE_NAME:sandbox}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_USERNAME:sandbox}
    password: ${JDBC_PASSWORD:sandbox}
    platform: postgres
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    table: migrations

